In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
import os

import json

import llama_cpp
import torch

from dotenv import load_dotenv
from openai import OpenAI

from curverag import utils
from curverag.curverag import CurveRAG, DEFAULT_ENTITY_TYPES, DEFAULT_GLINER_MODEL, DEFAULT_SENTENCE_TRANSFORMER_MODEL
from curverag.graph import KnowledgeGraph
from curverag.atth.kg_dataset import KGDataset
from curverag.atth.models.hyperbolic import AttH
from curverag.eval import evaluation, queries, context, expected_output

load_dotenv() 

True

# Explore dataset

In [18]:
with open('/Users/nathan/Documents/projects/datasets/2WikiMultihopQA/train.json', 'rb') as f:
    train = json.load(f)

with open('/Users/nathan/Documents/projects/datasets/2WikiMultihopQA/dev.json', 'rb') as f:
    dev = json.load(f)

with open('/Users/nathan/Documents/projects/datasets/2WikiMultihopQA/test.json', 'rb') as f:
    test = json.load(f)

In [19]:
train[0].keys()

dict_keys(['_id', 'type', 'question', 'context', 'supporting_facts', 'evidences', 'answer'])

In [20]:
train[0]['question']

'Are director of film Move (1970 Film) and director of film Méditerranée (1963 Film) from the same country?'

In [21]:
train[0]['answer']

'no'

In [22]:
train[0]['context']

[['Stuart Rosenberg',
  ['Stuart Rosenberg (August 11, 1927 – March 15, 2007) was an American film and television director whose motion pictures include "Cool Hand Luke" (1967), "Voyage of the Damned" (1976), "The Amityville Horror" (1979), and "The Pope of Greenwich Village" (1984).',
   'He was noted for his work with actor Paul Newman.']],
 ['Méditerranée (1963 film)',
  ['Méditerranée is a 1963 French experimental film directed by Jean-Daniel Pollet with assistance from Volker Schlöndorff.',
   'It was written by Philippe Sollers and produced by Barbet Schroeder, with music by Antione Duhamel.',
   'The 45 minute film is cited as one of Pollet\'s most influential films, which according to Jonathan Rosenbaum directly influenced Jean-Luc Goddard\'s "Contempt", released later the same year.',
   'Footage for the film was shot around the Mediterranean, including at a Greek temple, a Sicilian garden, the sea, and also features a fisherman, a bullfighter, and a girl on an operating table

# Run eval

In [23]:
api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

In [24]:
entity_types = ['people', 'locations', 'entities', 'movies', 'directors']
rag = CurveRAG(
    openai_client=client,
    entity_types=entity_types,
)

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

In [10]:
new_docs = []
for d in train[0]['context']:
    d_ = str(d).replace('[', '').replace(']', '. ').replace('\'', '')
    new_docs.append(d_)

In [25]:
new_docs = []
for d in train:
    d_ = str(d['context']).replace('[', '').replace(']', '. ').replace('\'', '')
    new_docs.append(d_)

In [26]:
rag.fit(new_docs[:100], dataset_name='movies')

creating graph


  1%|▍                                                                   | 1/138 [00:12<28:55, 12.67s/it]

upserting


  1%|▉                                                                   | 2/138 [00:21<23:42, 10.46s/it]

upserting


  2%|█▍                                                                  | 3/138 [00:31<23:05, 10.27s/it]

upserting


  3%|█▉                                                                  | 4/138 [00:44<25:24, 11.38s/it]

upserting


  4%|██▍                                                                 | 5/138 [00:51<21:24,  9.66s/it]

upserting


  4%|██▉                                                                 | 6/138 [01:00<20:49,  9.46s/it]

upserting


  5%|███▍                                                                | 7/138 [01:10<21:01,  9.63s/it]

upserting


  6%|███▉                                                                | 8/138 [01:18<19:29,  9.00s/it]

upserting


  7%|████▍                                                               | 9/138 [01:36<25:25, 11.82s/it]

upserting


  7%|████▊                                                              | 10/138 [01:43<22:26, 10.52s/it]

upserting


  8%|█████▎                                                             | 11/138 [01:50<19:59,  9.44s/it]

upserting


  9%|█████▊                                                             | 12/138 [01:58<19:03,  9.08s/it]

upserting


  9%|██████▎                                                            | 13/138 [02:11<21:12, 10.18s/it]

upserting


 10%|██████▊                                                            | 14/138 [02:23<22:15, 10.77s/it]

upserting


 11%|███████▎                                                           | 15/138 [02:30<19:35,  9.56s/it]

upserting


 12%|███████▊                                                           | 16/138 [02:43<21:25, 10.54s/it]

upserting


 12%|████████▎                                                          | 17/138 [02:56<22:56, 11.37s/it]

upserting


 13%|████████▋                                                          | 18/138 [03:05<21:17, 10.65s/it]

upserting


 14%|█████████▏                                                         | 19/138 [03:17<22:03, 11.12s/it]

upserting


 14%|█████████▋                                                         | 20/138 [03:23<18:27,  9.38s/it]

upserting


 15%|██████████▏                                                        | 21/138 [03:34<19:37, 10.07s/it]

upserting


 16%|██████████▋                                                        | 22/138 [03:38<15:52,  8.21s/it]

upserting


 17%|███████████▏                                                       | 23/138 [03:48<16:50,  8.79s/it]

upserting


 17%|███████████▋                                                       | 24/138 [03:58<17:20,  9.13s/it]

upserting


 18%|████████████▏                                                      | 25/138 [04:08<17:25,  9.26s/it]

upserting


 19%|████████████▌                                                      | 26/138 [04:13<15:16,  8.18s/it]

upserting


 20%|█████████████                                                      | 27/138 [04:23<15:41,  8.48s/it]

upserting


 20%|█████████████▌                                                     | 28/138 [04:33<16:29,  9.00s/it]

upserting


 21%|██████████████                                                     | 29/138 [04:41<15:41,  8.64s/it]

upserting


 22%|██████████████▌                                                    | 30/138 [04:52<16:52,  9.37s/it]

upserting


 22%|███████████████                                                    | 31/138 [05:08<20:33, 11.53s/it]

upserting


 23%|███████████████▌                                                   | 32/138 [05:19<20:09, 11.41s/it]

upserting


 24%|████████████████                                                   | 33/138 [05:23<16:01,  9.16s/it]

upserting


 25%|████████████████▌                                                  | 34/138 [05:30<14:44,  8.51s/it]

upserting


 25%|████████████████▉                                                  | 35/138 [05:46<18:08, 10.57s/it]

upserting


 26%|█████████████████▍                                                 | 36/138 [05:57<18:18, 10.77s/it]

upserting


 27%|█████████████████▉                                                 | 37/138 [06:05<16:37,  9.87s/it]

upserting


 28%|██████████████████▍                                                | 38/138 [06:14<16:11,  9.71s/it]

upserting


 28%|██████████████████▉                                                | 39/138 [06:23<15:46,  9.56s/it]

upserting


 29%|███████████████████▍                                               | 40/138 [06:35<16:36, 10.16s/it]

upserting


 30%|███████████████████▉                                               | 41/138 [06:45<16:22, 10.12s/it]

upserting


 30%|████████████████████▍                                              | 42/138 [06:57<17:14, 10.78s/it]

upserting


 31%|████████████████████▉                                              | 43/138 [07:07<16:27, 10.40s/it]

upserting


 32%|█████████████████████▎                                             | 44/138 [07:12<13:49,  8.82s/it]

upserting


 33%|█████████████████████▊                                             | 45/138 [07:24<15:26,  9.96s/it]

upserting


 33%|██████████████████████▎                                            | 46/138 [07:39<17:29, 11.41s/it]

upserting


 34%|██████████████████████▊                                            | 47/138 [07:49<16:35, 10.94s/it]

upserting


 35%|███████████████████████▎                                           | 48/138 [08:01<16:38, 11.10s/it]

upserting


 36%|███████████████████████▊                                           | 49/138 [08:17<18:59, 12.80s/it]

upserting


 36%|████████████████████████▎                                          | 50/138 [08:30<18:33, 12.65s/it]

upserting


 37%|████████████████████████▊                                          | 51/138 [08:33<14:05,  9.71s/it]

upserting


 38%|█████████████████████████▏                                         | 52/138 [08:41<13:36,  9.49s/it]

upserting


 38%|█████████████████████████▋                                         | 53/138 [08:54<14:47, 10.44s/it]

upserting


 39%|██████████████████████████▏                                        | 54/138 [09:00<12:38,  9.03s/it]

upserting


 40%|██████████████████████████▋                                        | 55/138 [09:13<14:20, 10.37s/it]

upserting


 41%|███████████████████████████▏                                       | 56/138 [09:25<14:47, 10.82s/it]

upserting


 41%|███████████████████████████▋                                       | 57/138 [09:39<15:55, 11.80s/it]

upserting


 42%|████████████████████████████▏                                      | 58/138 [09:50<15:24, 11.56s/it]

upserting


 43%|████████████████████████████▋                                      | 59/138 [10:00<14:25, 10.95s/it]

upserting


 43%|█████████████████████████████▏                                     | 60/138 [10:15<15:45, 12.12s/it]

upserting


 44%|█████████████████████████████▌                                     | 61/138 [10:26<15:18, 11.93s/it]

upserting


 45%|██████████████████████████████                                     | 62/138 [10:34<13:36, 10.74s/it]

upserting


 46%|██████████████████████████████▌                                    | 63/138 [10:53<16:18, 13.05s/it]

upserting


 46%|███████████████████████████████                                    | 64/138 [11:04<15:22, 12.47s/it]

upserting


 47%|███████████████████████████████▌                                   | 65/138 [11:10<12:48, 10.52s/it]

upserting


 48%|████████████████████████████████                                   | 66/138 [11:24<14:01, 11.69s/it]

upserting


 49%|████████████████████████████████▌                                  | 67/138 [11:42<15:54, 13.45s/it]

upserting


 49%|█████████████████████████████████                                  | 68/138 [11:52<14:27, 12.39s/it]

upserting


 50%|█████████████████████████████████▌                                 | 69/138 [12:02<13:43, 11.93s/it]

upserting


 51%|█████████████████████████████████▉                                 | 70/138 [12:16<13:55, 12.28s/it]

upserting


 51%|██████████████████████████████████▍                                | 71/138 [12:25<12:50, 11.50s/it]

upserting


 52%|██████████████████████████████████▉                                | 72/138 [13:23<27:53, 25.36s/it]

upserting


 53%|███████████████████████████████████▍                               | 73/138 [13:40<24:43, 22.82s/it]

upserting


 54%|███████████████████████████████████▉                               | 74/138 [13:51<20:34, 19.29s/it]

upserting


 54%|████████████████████████████████████▍                              | 75/138 [14:01<17:21, 16.53s/it]

upserting


 55%|████████████████████████████████████▉                              | 76/138 [14:14<15:55, 15.41s/it]

upserting


 56%|█████████████████████████████████████▍                             | 77/138 [14:25<14:22, 14.14s/it]

upserting


 57%|█████████████████████████████████████▊                             | 78/138 [14:37<13:32, 13.54s/it]

upserting


 57%|██████████████████████████████████████▎                            | 79/138 [14:52<13:47, 14.02s/it]

upserting


 58%|██████████████████████████████████████▊                            | 80/138 [15:01<12:04, 12.49s/it]

upserting


 59%|███████████████████████████████████████▎                           | 81/138 [15:42<19:57, 21.01s/it]

upserting


 59%|███████████████████████████████████████▊                           | 82/138 [15:44<14:24, 15.43s/it]

upserting


 60%|████████████████████████████████████████▎                          | 83/138 [15:59<13:47, 15.04s/it]

upserting


 61%|████████████████████████████████████████▊                          | 84/138 [16:06<11:32, 12.83s/it]

upserting


 62%|█████████████████████████████████████████▎                         | 85/138 [16:09<08:48,  9.97s/it]

upserting


 62%|█████████████████████████████████████████▊                         | 86/138 [16:19<08:37,  9.96s/it]

upserting


 63%|██████████████████████████████████████████▏                        | 87/138 [16:26<07:32,  8.88s/it]

upserting


 64%|██████████████████████████████████████████▋                        | 88/138 [16:40<08:41, 10.42s/it]

upserting


 64%|███████████████████████████████████████████▏                       | 89/138 [16:53<09:15, 11.34s/it]

upserting


 65%|███████████████████████████████████████████▋                       | 90/138 [16:59<07:41,  9.61s/it]

upserting


 66%|████████████████████████████████████████████▏                      | 91/138 [17:08<07:27,  9.53s/it]

upserting


 67%|████████████████████████████████████████████▋                      | 92/138 [17:17<07:06,  9.27s/it]

upserting


 67%|█████████████████████████████████████████████▏                     | 93/138 [17:33<08:35, 11.46s/it]

upserting


 68%|█████████████████████████████████████████████▋                     | 94/138 [17:43<07:53, 10.77s/it]

upserting


 69%|██████████████████████████████████████████████                     | 95/138 [17:54<07:55, 11.05s/it]

upserting


 70%|██████████████████████████████████████████████▌                    | 96/138 [18:00<06:40,  9.53s/it]

upserting


 70%|███████████████████████████████████████████████                    | 97/138 [18:12<06:51, 10.04s/it]

upserting


 71%|███████████████████████████████████████████████▌                   | 98/138 [18:23<06:56, 10.42s/it]

upserting


 72%|████████████████████████████████████████████████                   | 99/138 [18:33<06:40, 10.27s/it]

upserting


 72%|███████████████████████████████████████████████▊                  | 100/138 [18:48<07:24, 11.70s/it]

upserting


 73%|████████████████████████████████████████████████▎                 | 101/138 [18:53<05:59,  9.71s/it]

upserting


 74%|████████████████████████████████████████████████▊                 | 102/138 [19:56<15:31, 25.88s/it]

upserting


 75%|█████████████████████████████████████████████████▎                | 103/138 [20:07<12:26, 21.33s/it]

upserting


 75%|█████████████████████████████████████████████████▋                | 104/138 [20:18<10:16, 18.13s/it]

upserting


 76%|██████████████████████████████████████████████████▏               | 105/138 [20:32<09:21, 17.01s/it]

upserting


 77%|██████████████████████████████████████████████████▋               | 106/138 [20:39<07:25, 13.91s/it]

upserting


 78%|███████████████████████████████████████████████████▏              | 107/138 [20:52<07:04, 13.70s/it]

upserting


 78%|███████████████████████████████████████████████████▋              | 108/138 [21:06<06:53, 13.77s/it]

upserting


 79%|████████████████████████████████████████████████████▏             | 109/138 [21:14<05:50, 12.10s/it]

upserting


 80%|████████████████████████████████████████████████████▌             | 110/138 [21:21<04:52, 10.46s/it]

upserting


 80%|█████████████████████████████████████████████████████             | 111/138 [21:39<05:42, 12.68s/it]

upserting


 81%|█████████████████████████████████████████████████████▌            | 112/138 [21:47<04:53, 11.29s/it]

upserting


 82%|██████████████████████████████████████████████████████            | 113/138 [22:00<04:56, 11.84s/it]

upserting


 83%|██████████████████████████████████████████████████████▌           | 114/138 [22:37<07:45, 19.38s/it]

upserting


 83%|███████████████████████████████████████████████████████           | 115/138 [22:45<06:06, 15.93s/it]

upserting


 84%|███████████████████████████████████████████████████████▍          | 116/138 [22:54<05:03, 13.82s/it]

upserting


 85%|███████████████████████████████████████████████████████▉          | 117/138 [23:08<04:54, 14.01s/it]

upserting


 86%|████████████████████████████████████████████████████████▍         | 118/138 [23:22<04:40, 14.05s/it]

upserting


 86%|████████████████████████████████████████████████████████▉         | 119/138 [23:35<04:21, 13.76s/it]

upserting


 87%|█████████████████████████████████████████████████████████▍        | 120/138 [23:41<03:21, 11.21s/it]

upserting


 88%|█████████████████████████████████████████████████████████▊        | 121/138 [23:52<03:10, 11.18s/it]

upserting


 88%|██████████████████████████████████████████████████████████▎       | 122/138 [23:59<02:42, 10.13s/it]

upserting


 89%|██████████████████████████████████████████████████████████▊       | 123/138 [24:08<02:23,  9.59s/it]

upserting


 90%|███████████████████████████████████████████████████████████▎      | 124/138 [24:22<02:34, 11.02s/it]

upserting


 91%|███████████████████████████████████████████████████████████▊      | 125/138 [24:32<02:17, 10.60s/it]

upserting


 91%|████████████████████████████████████████████████████████████▎     | 126/138 [24:50<02:34, 12.91s/it]

upserting


 92%|████████████████████████████████████████████████████████████▋     | 127/138 [25:01<02:15, 12.30s/it]

upserting


 93%|█████████████████████████████████████████████████████████████▏    | 128/138 [25:14<02:06, 12.61s/it]

upserting


 93%|█████████████████████████████████████████████████████████████▋    | 129/138 [25:29<01:58, 13.15s/it]

upserting


 94%|██████████████████████████████████████████████████████████████▏   | 130/138 [25:44<01:50, 13.85s/it]

upserting


 95%|██████████████████████████████████████████████████████████████▋   | 131/138 [25:56<01:33, 13.38s/it]

upserting


 96%|███████████████████████████████████████████████████████████████▏  | 132/138 [26:09<01:19, 13.29s/it]

upserting


 96%|███████████████████████████████████████████████████████████████▌  | 133/138 [26:23<01:06, 13.25s/it]

upserting


 97%|████████████████████████████████████████████████████████████████  | 134/138 [26:35<00:52, 13.07s/it]

upserting


 98%|████████████████████████████████████████████████████████████████▌ | 135/138 [26:46<00:37, 12.44s/it]

upserting


 99%|█████████████████████████████████████████████████████████████████ | 136/138 [27:02<00:26, 13.44s/it]

upserting


 99%|█████████████████████████████████████████████████████████████████▌| 137/138 [27:13<00:12, 12.71s/it]

upserting


100%|██████████████████████████████████████████████████████████████████| 138/138 [27:21<00:00, 11.89s/it]
2025-06-22 12:43:53,856 INFO     Saving logs in: ./logs/06_22/movies/AttH_12_43_53
2025-06-22 12:43:53,857 INFO     	 (799, 484, 799)
2025-06-22 12:43:53,927 INFO     Total number of parameters 3221082
2025-06-22 12:43:53,931 INFO     	 Start training


upserting
num nodes 799
unique node ids {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214

train loss: 100%|██████████████████████████████████████| 1252/1252 [00:10<00:00, 124.46ex/s, loss=2.0961]
2025-06-22 12:44:03,994 INFO     	 Epoch 0 | average train loss: 1.3923
2025-06-22 12:44:04,095 INFO     	 Epoch 0 | average valid loss: 1.7016
train loss: 100%|██████████████████████████████████████| 1252/1252 [00:07<00:00, 160.66ex/s, loss=1.6575]
2025-06-22 12:44:11,894 INFO     	 Epoch 1 | average train loss: 1.7686
2025-06-22 12:44:11,990 INFO     	 Epoch 1 | average valid loss: 0.9531
train loss: 100%|██████████████████████████████████████| 1252/1252 [00:06<00:00, 197.78ex/s, loss=0.8719]
2025-06-22 12:44:18,322 INFO     	 Epoch 2 | average train loss: 1.0416
2025-06-22 12:44:18,413 INFO     	 Epoch 2 | average valid loss: 0.4587
2025-06-22 12:44:18,431 INFO     	 valid MR: 201.85 | MRR: 0.013 | H@1: 0.000 | H@3: 0.000 | H@10: 0.013
2025-06-22 12:44:18,432 INFO     	 Epoch 2 | average valid mmr: 0.0126
2025-06-22 12:44:18,432 INFO     	 Saving model at epoch 2 in ./logs/06_22

returning model


Batches:   0%|          | 0/25 [00:00<?, ?it/s]

In [27]:
rag.graph.nodes

[Node(id=1, name='Stuart Rosenberg', description='American film and television director American film and television director', alias=['Stuart Rosenberg (August 11, 1927 – March 15, 2007)', 'Stuart Rosenberg'], additional_information=["Directed 'Cool Hand Luke', 'Voyage of the Damned', 'The Amityville Horror', 'The Pope of Greenwich Village'"]),
 Node(id=2, name='Méditerranée', description='1963 French experimental film', alias=['Méditerranée (1963 film)'], additional_information=['Directed by Jean-Daniel Pollet', 'Written by Philippe Sollers', 'Produced by Barbet Schroeder']),
 Node(id=3, name='Move', description='1970 American comedy film', alias=['Move (1970 film)'], additional_information=['Starring Elliott Gould, Paula Prentiss, and Geneviève Waïte', 'Directed by Stuart Rosenberg']),
 Node(id=4, name='Ian Barry', description='Australian director of film and TV Australian director of film and TV Australian director of film and TV Australian director of film and TV Australian direct

In [28]:
rag.graph.edges

[Edge(source=1, target=3, name='directed', is_directed=True, description='Directed the film', notes=["Directed 'Move' (1970)"]),
 Edge(source=1, target=2, name='directed', is_directed=True, description='Directed the film', notes=["Directed 'Méditerranée' with assistance"]),
 Edge(source=2, target=9, name='influenced', is_directed=False, description='Influenced another film', notes=["Influenced 'Contempt' by Jean-Luc Godard"]),
 Edge(source=9, target=4, name='associated', is_directed=False, description='Approaches to filmmaking', notes=['Burlesque and melancholic elements', 'Based on texts by French poet Francis Ponge']),
 Edge(source=11, target=13, name='directed', is_directed=True, description='Directed the film', notes=["Directed 'The Falcon Takes Over'"]),
 Edge(source=12, target=14, name='directed', is_directed=True, description='Directed the film', notes=["Directed 'The Falcon Strikes Back'"]),
 Edge(source=13, target=11, name='starred', is_directed=False, description='Starred in 

In [29]:
print('Question:', train[0]['question'])
resp = rag.query(train[0]['question'], traversal = 'pp')
resp

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


Question: Are director of film Move (1970 Film) and director of film Méditerranée (1963 Film) from the same country?
entities ['Move', 'Méditerranée']
Are AUX VBP
director NOUN NN
of ADP IN
film NOUN NN
Move PROPN NNP
( PUNCT -LRB-
1970 NUM CD
Film PROPN NNP
) PUNCT -RRB-
and CCONJ CC
director NOUN NN
of ADP IN
film NOUN NN
Méditerranée PROPN NNP
( PUNCT -LRB-
1963 NUM CD
Film PROPN NNP
) PUNCT -RRB-
from ADP IN
the DET DT
same ADJ JJ
country NOUN NN
? PUNCT .
pos_tags ['director', 'film', 'Move', 'Film', 'director', 'film', 'Méditerranée', 'Film', 'country']


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

graph nodes retrieved ['Méditerranée', 'Move', 'At the Movies', 'American Film Institute', 'The Actors', 'The Da Vinci Code (film)', 'A Far Country', 'Committed (film)', 'Blowback (film)', 'Clouds (film)']
entites for edges ['Move', 'Méditerranée', 'director', 'film', 'Move', 'Film', 'director', 'film', 'Méditerranée', 'Film', 'country']


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/25 [00:00<?, ?it/s]

similar_edges ['influenced', 'associated', 'directed', 'starred', 'reprises role', 'produced']
similar_node_ids [140, 330, 339, 401, 2, 764, 765, 3, 131, 336]
similar_node_ids graph nodes retrieved ['Méditerranée', 'Move', 'At the Movies', 'Neil Young', 'Judy Garland', 'American Film Institute', 'A Pretty Girl Milking Her Cow', 'The Actors', 'Committed (film)', 'Blowback (film)']
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!

2025-06-22 12:50:16,841 INFO     HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"


'The director of the film *Méditerranée* (1963) is Jean-Daniel Pollet, and the director of the film *Move* (1970) is Stuart Rosenberg. *Méditerranée* is a French film, indicating that Jean-Daniel Pollet is from France. In contrast, *Move* is an American film, suggesting that Stuart Rosenberg is from the United States. Therefore, the directors of these two films are not from the same country.'

In [30]:
print('Question:', train[0]['question'])
resp = rag.query(train[0]['question'])
resp

Question: Are director of film Move (1970 Film) and director of film Méditerranée (1963 Film) from the same country?
entities ['Move', 'Méditerranée']
Are AUX VBP
director NOUN NN
of ADP IN
film NOUN NN
Move PROPN NNP
( PUNCT -LRB-
1970 NUM CD
Film PROPN NNP
) PUNCT -RRB-
and CCONJ CC
director NOUN NN
of ADP IN
film NOUN NN
Méditerranée PROPN NNP
( PUNCT -LRB-
1963 NUM CD
Film PROPN NNP
) PUNCT -RRB-
from ADP IN
the DET DT
same ADJ JJ
country NOUN NN
? PUNCT .
pos_tags ['director', 'film', 'Move', 'Film', 'director', 'film', 'Méditerranée', 'Film', 'country']


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

graph nodes retrieved ['Méditerranée', 'Move', 'At the Movies', 'American Film Institute', 'The Actors', 'The Da Vinci Code (film)', 'A Far Country', 'Committed (film)', 'Blowback (film)', 'Clouds (film)']
scores tensor([1.2203, 1.3070, 1.3187, 1.3485, 1.4398, 1.4547, 1.4754, 1.5413, 1.5517,
        1.5782], dtype=torch.float64)
scores tensor([2.1295, 2.2235, 2.2241, 2.2264, 2.3177, 2.3220, 2.4058, 2.4134, 2.4222,
        2.4255], dtype=torch.float64)
scores tensor([0.9095, 0.9110, 0.9120, 0.9147, 0.9166, 0.9187, 0.9194, 0.9206, 0.9215,
        0.9226], dtype=torch.float64)
scores tensor([1.0979, 1.2987, 1.3497, 1.3790, 1.4293, 1.4593, 1.4777, 1.5189, 1.5224,
        1.5495], dtype=torch.float64)
scores tensor([1.0992, 1.9681, 1.9968, 2.0183, 2.0561, 2.0810, 2.1175, 2.1190, 2.1274,
        2.1335], dtype=torch.float64)
scores tensor([2.2994e-07, 2.7842e+00, 2.8291e+00, 2.8668e+00, 2.9589e+00, 2.9795e+00,
        2.9971e+00, 3.0077e+00, 3.0098e+00, 3.0137e+00], dtype=torch.float64)
scor

2025-06-22 12:57:27,478 INFO     HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"


'The director of the film *Move* (1970) is Stuart Rosenberg, who is American, while the director of *Méditerranée* (1963) is Jean-Daniel Pollet, who is French. Therefore, they are not from the same country, as one is from the United States and the other from France. [Sources: 1, 2, 3]'

In [24]:
print('Question:', queries[1])
resp = rag.query(queries[1])
resp

Question: What gender is Jill?Give me the character arc of Sam
entities ['Jill', 'Sam']


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[[np.int64(1), np.int64(2)]]
node_ids [tensor([9, 7]), tensor([4, 0, 5])]
node_ids [9, 7, 4, 0, 5]
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************

You are a helpful assistant analyzing the given input data to provide an helpful response to the user query.

# USER QUERY
What gender is Jill?Give me the character arc of Sam

# Context:
KnowledgeGraph Overview
  There are 6 entities and 7 relationships in this graph.

Entities in the graph:
  • 'Jill':
      The entity has the following description: Jill is an adult sibling of Jack.
      It can also be referred to as: Jill
      It has the following additional 

Llama.generate: 1005 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    9163.97 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =    9254.43 ms /   100 runs   (   92.54 ms per token,    10.81 tokens per second)
llama_perf_context_print:       total time =    9668.53 ms /   101 tokens


'Jill is an adult sibling of Jack. As for the character arc of Sam, Sam is a friend of Jack and Jill, and they helped Sam find love. Sam then moved to Romania with their friend [1]. Sam found love in Romania, marking a significant change in their life [2].\n\nReferences:\n[1] Entity: Romania\n[2] Relationship: Sam moved to Romania with their friend\n\nNote: The answer is based on the information provided in the input data, and it is'

In [25]:
print('Question:', queries[2])
resp = rag.query(queries[2])
resp

Question: What location is the story set in
entities []


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[[]]
node_ids []
node_ids []

You are a helpful assistant analyzing the given input data to provide an helpful response to the user query.

# USER QUERY
What location is the story set in

# Context:
KnowledgeGraph Overview
  There are 0 entities and 0 relationships in this graph.

Entities in the graph:

Relationships between nodes:



# INSTRUCTIONS
Your goal is to provide a response to the user query using the relevant information in the input data:
- the "Entities" and "Relationships" tables contain high-level information. Use these tables to identify the most important entities and relationships to respond to the query.
- the "Sources" list contains raw text sources to help answer the query. It may contain noisy data, so pay attention when analyzing it.

Follow these steps:
1. Read and understand the user query.
2. Look at the "Entities" and "Relationships" tables to get a general sense of the data and understand which information is the most relevant to answer the query.
3. Carefu

Llama.generate: 28 prefix-match hit, remaining 333 prompt tokens to eval
llama_perf_context_print:        load time =    9163.97 ms
llama_perf_context_print: prompt eval time =    3022.72 ms /   333 tokens (    9.08 ms per token,   110.17 tokens per second)
llama_perf_context_print:        eval time =    4559.04 ms /    99 runs   (   46.05 ms per token,    21.72 tokens per second)
llama_perf_context_print:       total time =    7756.66 ms /   432 tokens


"Based on the given input data, no location is mentioned in the data. Therefore, it is not possible to determine the location of the story based on the provided information. [1]\n\nSource: [1] - There is no source ID provided in the input data. \n\nNote: I've followed the instructions and tried my best to provide a helpful response to the user query. Please let me know if I can improve anything. \n\nPlease let me know if the response is accurate and if there's"

In [119]:
print('Question:', queries[3])
resp = rag.query(queries[3])
resp

Question: What location is the story set in
entities []


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

graph nodes retrieved []
Found no embedding indx for entities, doing non KG-RAG result


'N/A'

In [29]:
print('Question:', queries[4])
resp = rag.query(queries[4])
resp

Question: Tell me how old Jack is, what the gender of Jill is, and then give me the character arcs of Sam and where the stoty is set
entities ['Jack', 'Jill', 'Sam']


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[[np.int64(0), np.int64(1), np.int64(2)]]
node_ids [tensor([4, 2]), tensor([9, 7]), tensor([4, 0, 5])]
node_ids [4, 2, 9, 7, 4, 0, 5]
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************
***************************************!!******************************

You are a helpful assistant analyzing the given input data to provide an helpful response to the user query.

# USER QUERY
Tell me how old Jack is, what the gender of Jill is, and then give me the character arcs of Sam and where the stoty is set

# Context:
KnowledgeGraph Overview
  There are 7 entities and 10 relationships in this graph.

Entities in the gra

Llama.generate: 57 prefix-match hit, remaining 1147 prompt tokens to eval
llama_perf_context_print:        load time =    9163.97 ms
llama_perf_context_print: prompt eval time =   10635.08 ms /  1147 tokens (    9.27 ms per token,   107.85 tokens per second)
llama_perf_context_print:        eval time =    4664.64 ms /    99 runs   (   47.12 ms per token,    21.22 tokens per second)
llama_perf_context_print:       total time =   15811.75 ms /  1246 tokens


"Based on the given data, we can answer the user query as follows:\nJack is 45 years old [1]. The gender of Jill is not explicitly mentioned in the given data, so we cannot determine it. As for Sam's character arc, we do not have enough information to provide a comprehensive analysis. The story is set in Romania [2], where Sam and their friend moved to. \n\nReferences:\n[1] - Entity description of Jack\n[2] - Relationship between Sam and Romania"

# networkx

In [120]:
import networkx as nx
import numpy as np
import scipy as sp

In [174]:
np.random.randint(10)

5

In [175]:
G = nx.Graph()
G.add_nodes_from([n.id for n in rag.graph.nodes])
edges = [(e.source, e.target, {'e_type':e.name, 'weight':np.random.randint(10)}) for e in rag.graph.edges]
G.add_edges_from(edges)
weight= 'weight'

In [176]:
G.edges(data=True)

EdgeDataView([(1, 10, {'e_type': 'directed', 'weight': 9}), (2, 3, {'e_type': 'directed', 'weight': 8}), (2, 4, {'e_type': 'assisted', 'weight': 4}), (2, 5, {'e_type': 'written by', 'weight': 6}), (2, 6, {'e_type': 'produced by', 'weight': 0}), (2, 7, {'e_type': 'music by', 'weight': 7}), (2, 8, {'e_type': 'influenced', 'weight': 1}), (8, 9, {'e_type': 'influenced', 'weight': 3}), (10, 11, {'e_type': 'starring', 'weight': 6}), (10, 12, {'e_type': 'starring', 'weight': 5}), (10, 13, {'e_type': 'starring', 'weight': 3}), (10, 14, {'e_type': 'written by', 'weight': 7}), (10, 15, {'e_type': 'written by', 'weight': 6}), (14, 14, {'e_type': 'adapted from', 'weight': 5})])

In [162]:
G.number_of_nodes()

21

In [163]:
N = len(G)
N

21

In [177]:
nodelist = list(G)
nodelist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [178]:
A = nx.to_scipy_sparse_array(G, nodelist=nodelist, weight=weight, dtype=float)
A

<Compressed Sparse Row sparse array of dtype 'float64'
	with 27 stored elements and shape (21, 21)>

In [179]:
A.toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 9., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 8., 4., 6., 0., 7., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [9., 0., 0., 0., 0., 0., 0., 0., 0., 0., 6., 5., 3., 7., 6., 0.,
        0., 0., 0.,

In [166]:
A.toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
        0., 0., 0.,

In [180]:
S = A.sum(axis=1)
S

array([ 9., 26.,  8.,  4.,  6.,  0.,  7.,  4.,  3., 36.,  6.,  5.,  3.,
       12.,  6.,  0.,  0.,  0.,  0.,  0.,  0.])

In [181]:
1/S[S != 0]

array([0.11111111, 0.03846154, 0.125     , 0.25      , 0.16666667,
       0.14285714, 0.25      , 0.33333333, 0.02777778, 0.16666667,
       0.2       , 0.33333333, 0.08333333, 0.16666667])

In [182]:
S[S != 0] = 1.0 / S[S != 0]
S

array([0.11111111, 0.03846154, 0.125     , 0.25      , 0.16666667,
       0.        , 0.14285714, 0.25      , 0.33333333, 0.02777778,
       0.16666667, 0.2       , 0.33333333, 0.08333333, 0.16666667,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [183]:
Q = sp.sparse.csr_array(sp.sparse.spdiags(S.T, 0, *A.shape))
Q

<Compressed Sparse Row sparse array of dtype 'float64'
	with 14 stored elements and shape (21, 21)>

In [184]:
Q.toarray()

array([[0.11111111, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.03846154, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.125     , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.25      , 0.        ,
        0.        , 0.        , 0.        , 0.       

In [185]:
A = Q @ A
A

<Compressed Sparse Row sparse array of dtype 'float64'
	with 25 stored elements and shape (21, 21)>

In [186]:
A = Q @ A


In [187]:
A.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.11111111,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.01183432, 0.00591716, 0.00887574,
        0.        , 0.01035503, 0.00147929, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.125     , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.25      , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.       

In [188]:
x = np.repeat(1.0 / N, N)
x

array([0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905])

In [189]:
p = np.repeat(1.0 / N, N)
p

array([0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905])

In [190]:
dangling_weights = p

In [151]:
is_dangling = np.where(S == 0)[0]
is_dangling

array([15, 16, 17, 18, 19, 20])

In [152]:
0.5*0.1

0.05

In [153]:
alpha = 0.85

In [154]:
x

array([0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905, 0.04761905, 0.04761905, 0.04761905, 0.04761905,
       0.04761905])

In [160]:
A.toarray()#.sum(axis=1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.02777778, 0.02777778, 0.02777778,
        0.02777778, 0.02777778, 0.02777778, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.       

In [118]:
0.04761905*1

0.04761905

In [116]:
x @ A

array([0.00793651, 0.26190476, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.05555556, 0.02380952, 0.26190476,
       0.00793651, 0.00793651, 0.00793651, 0.03174603, 0.00793651,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [104]:
x_new = alpha * (x @ A + sum(x[is_dangling]) * dangling_weights) + (1 - alpha) * p


In [108]:
x_new

array([0.02545351, 0.24132653, 0.02545351, 0.02545351, 0.02545351,
       0.02545351, 0.02545351, 0.06592971, 0.03894558, 0.24132653,
       0.02545351, 0.02545351, 0.02545351, 0.04569161, 0.02545351,
       0.01870748, 0.01870748, 0.01870748, 0.01870748, 0.01870748,
       0.01870748])

In [ ]:
edge_types