In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch

from curverag.atth.kg_dataset import KGDataset
from curverag.atth.models.hyperbolic import AttH
from curverag.atth.utils.hyperbolic import hyp_distance

In [3]:
dataset_path = './data/medical_docs'
dataset = KGDataset(dataset_path, debug=False, name='medical_docs')

In [4]:
sizes = dataset.get_shape()

In [5]:
sizes

(45, 48, 45)

In [6]:
model = AttH(sizes=sizes)
model_path = '/Users/nathan/Documents/projects/curve_rag/logs/05_01/medical_docs/AttH_23_03_31/model.pt'
model.load_state_dict(torch.load(model_path, weights_only=True))
model.eval()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/nathan/Documents/projects/curve_rag/logs/05_01/medical_docs/AttH_23_03_31/model.pt'

In [29]:
entity_embeddings = model.entity.weight.data.cpu().numpy()

In [41]:
entities_embs_1 = model.entity.weight.data[:10]
entities_embs_2 = model.entity.weight.data[:10]

In [85]:
type(entities_embs_2)

torch.Tensor

In [83]:
model.entity.weight.data[[0, 4, 5]]

tensor([[-0.1009,  0.0997,  0.1011,  ...,  0.0994, -0.0992, -0.0872],
        [ 0.0972,  0.1023, -0.0994,  ...,  0.0991,  0.0905,  0.0982],
        [-0.0989,  0.1009, -0.0952,  ..., -0.0977,  0.0999,  0.0987]],
       dtype=torch.float64)

In [75]:
c = torch.tensor([1.0], dtype=model.entity.weight.data.dtype)

In [76]:
distances = hyp_distance(entities_embs_1, entities_embs_2, c, eval_mode=True)

In [77]:
distances.shape

torch.Size([10, 10])

In [78]:
distances

tensor([[1.5821e-08, 1.0228e+00, 1.0387e+00, 9.9058e-01, 1.0150e+00, 1.0115e+00,
         1.0042e+00, 9.8303e-01, 9.6826e-01, 1.0056e+00],
        [1.0228e+00, 1.8271e-08, 9.8176e-01, 9.7381e-01, 9.9466e-01, 9.7279e-01,
         9.6559e-01, 9.7851e-01, 9.7131e-01, 9.8186e-01],
        [1.0387e+00, 9.8176e-01, 0.0000e+00, 1.0204e+00, 9.9740e-01, 9.7583e-01,
         9.7125e-01, 1.0017e+00, 1.0013e+00, 1.0143e+00],
        [9.9058e-01, 9.7381e-01, 1.0204e+00, 1.8000e-08, 9.7836e-01, 9.7415e-01,
         9.6307e-01, 9.6381e-01, 9.7829e-01, 9.6840e-01],
        [1.0150e+00, 9.9466e-01, 9.9740e-01, 9.7836e-01,        nan, 9.7398e-01,
         9.7391e-01, 9.6891e-01, 1.0059e+00, 9.7293e-01],
        [1.0115e+00, 9.7279e-01, 9.7583e-01, 9.7415e-01, 9.7398e-01,        nan,
         9.9011e-01, 9.7637e-01, 9.7809e-01, 9.8384e-01],
        [1.0042e+00, 9.6559e-01, 9.7125e-01, 9.6307e-01, 9.7391e-01, 9.9011e-01,
         0.0000e+00, 9.8260e-01, 9.6894e-01, 1.0141e+00],
        [9.8303e-01, 9.7851

In [79]:
distances[0]

tensor([1.5821e-08, 1.0228e+00, 1.0387e+00, 9.9058e-01, 1.0150e+00, 1.0115e+00,
        1.0042e+00, 9.8303e-01, 9.6826e-01, 1.0056e+00], dtype=torch.float64)

In [80]:
scores, indices = torch.topk(distances[2], 5, largest=False)
print(indices)

tensor([2, 6, 5, 1, 4])


In [81]:
threshold = 0.9
mask = scores > threshold
print(mask)
filtered_vals = scores[mask]
filtered_indices = indices[mask]
filtered_indices

tensor([False,  True,  True,  True,  True])


tensor([6, 5, 1, 4])